# -*- coding: utf-8 -*-
"""BackTest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aVzVoKVB4rrvcZfiOxTa-wZi6hfTO2QD
"""

import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from itertools import product

# --- Load and Preprocess Data ---
def load_data(filepath):
    df = pd.read_csv(filepath)
    # Keep first message per publisher_id per ts_event
    df = df.sort_values('ts_event').groupby(['ts_event', 'publisher_id']).first().reset_index()
    # Extract best ask (ask_px_00) and size (ask_sz_00)
    df = df[['ts_event', 'publisher_id', 'ask_px_00', 'ask_sz_00']]
    return df

# --- Static Cost Model Allocator ---
def allocate(order_size, venues, lambda_over, lambda_under, theta_queue):
    step = 100  # Search in 100-share increments
    splits = [[]]

    for v in range(len(venues)):
        new_splits = []
        for alloc in splits:
            used = sum(alloc)
            max_v = min(order_size - used, venues[v]['ask_sz_00'])
            for q in range(0, max_v + 1, step):
                new_splits.append(alloc + [q])
        splits = new_splits

    best_cost = float('inf')
    best_split = []
    for alloc in splits:
        if sum(alloc) != order_size:
            continue
        cost = compute_cost(alloc, venues, order_size, lambda_over, lambda_under, theta_queue)
        if cost < best_cost:
            best_cost = cost
            best_split = alloc
    return best_split

def compute_cost(split, venues, order_size, lambda_over, lambda_under, theta_queue):
    executed = 0
    cash_spent = 0
    for i in range(len(split)):
        exe = min(split[i], venues[i]['ask_sz_00'])
        executed += exe
        cash_spent += exe * venues[i]['ask_px_00']

    underfill = max(order_size - executed, 0)
    overfill = max(executed - order_size, 0)
    risk_pen = theta_queue * (underfill + overfill)
    cost_pen = lambda_under * underfill + lambda_over * overfill
    return cash_spent + risk_pen + cost_pen

# --- Backtest Execution ---
def backtest(df, order_size, lambda_over, lambda_under, theta_queue):
    remaining = order_size
    cash_spent = 0
    shares_filled = 0
    snapshots = df.groupby('ts_event')

    for ts, snapshot in snapshots:
        if remaining <= 0:
            break
        venues = snapshot.to_dict('records')
        alloc = allocate(remaining, venues, lambda_over, lambda_under, theta_queue)

        for i, qty in enumerate(alloc):
            if qty == 0:
                continue
            venue = venues[i]
            fill = min(qty, venue['ask_sz_00'])
            cash_spent += fill * venue['ask_px_00']
            remaining -= fill

    avg_price = cash_spent / (order_size - remaining) if (order_size - remaining) > 0 else 0
    return cash_spent, avg_price

# --- Baseline Strategies ---
def best_ask(df, order_size):
    snapshots = df.groupby('ts_event')
    remaining = order_size
    cash_spent = 0

    for ts, snapshot in snapshots:
        if remaining <= 0:
            break
        best_venue = snapshot.loc[snapshot['ask_px_00'].idxmin()]
        fill = min(remaining, best_venue['ask_sz_00'])
        cash_spent += fill * best_venue['ask_px_00']
        remaining -= fill

    avg_price = cash_spent / (order_size - remaining) if (order_size - remaining) > 0 else 0
    return cash_spent, avg_price

def twap(df, order_size):
    snapshots = df.groupby('ts_event')
    total_snapshots = len(snapshots)
    shares_per_snap = order_size / total_snapshots
    cash_spent = 0

    for ts, snapshot in snapshots:
        avg_price = snapshot['ask_px_00'].mean()
        cash_spent += shares_per_snap * avg_price

    avg_price = cash_spent / order_size
    return cash_spent, avg_price

def vwap(df, order_size):
    total_volume = df['ask_sz_00'].sum()
    if total_volume == 0:
        return 0, 0
    vwap_price = (df['ask_px_00'] * df['ask_sz_00']).sum() / total_volume
    cash_spent = order_size * vwap_price
    return cash_spent, vwap_price

# --- Parameter Optimization ---
def optimize(df, order_size):
    param_grid = {
        'lambda_over': np.linspace(0.01, 0.1, 3),
        'lambda_under': np.linspace(0.01, 0.1, 3),
        'theta_queue': np.linspace(0.001, 0.01, 3)
    }
    best_params = None
    best_cash = float('inf')
    best_avg_price = 0

    for params in product(*param_grid.values()):
        lambda_over, lambda_under, theta_queue = params
        cash, avg_price = backtest(df, order_size, lambda_over, lambda_under, theta_queue)
        if cash < best_cash:
            best_cash = cash
            best_avg_price = avg_price
            best_params = {
                'lambda_over': lambda_over,
                'lambda_under': lambda_under,
                'theta_queue': theta_queue
            }
    return best_params, best_cash, best_avg_price

# --- Main Execution ---
if __name__ == "__main__":
    # Load data
    df = load_data('/content/l1_day.csv')
    order_size = 5000

    # Optimize parameters
    best_params, best_cash, best_avg_price = optimize(df, order_size)

    # Baseline strategies
    best_ask_cash, best_ask_price = best_ask(df, order_size)
    twap_cash, twap_price = twap(df, order_size)
    vwap_cash, vwap_price = vwap(df, order_size)

    # Compute savings (in basis points)
    def bps_savings(base, ours):
        return ((base - ours) / base) * 10000 if base != 0 else 0

    savings_best_ask = bps_savings(best_ask_cash, best_cash)
    savings_twap = bps_savings(twap_cash, best_cash)
    savings_vwap = bps_savings(vwap_cash, best_cash)

    # Output JSON
    output = {
        "best_params": best_params,
        "best_cash_spent": best_cash,
        "best_avg_price": best_avg_price,
        "baselines": {
            "best_ask": {"cash_spent": best_ask_cash, "avg_price": best_ask_price},
            "twap": {"cash_spent": twap_cash, "avg_price": twap_price},
            "vwap": {"cash_spent": vwap_cash, "avg_price": vwap_price}
        },
        "savings_bps": {
            "vs_best_ask": savings_best_ask,
            "vs_twap": savings_twap,
            "vs_vwap": savings_vwap
        }
    }

    print(json.dumps(output, indent=2))

    # Plot cumulative cost (optional)
    plt.figure(figsize=(10, 6))
    plt.plot([best_cash, best_ask_cash, twap_cash, vwap_cash], marker='o')
    plt.xticks([0, 1, 2, 3], ['SOR', 'Best Ask', 'TWAP', 'VWAP'])
    plt.ylabel('Cash Spent')
    plt.title('Execution Cost Comparison')
    plt.savefig('results.png')